name: Deploy Next.js to VPS

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Matches the Node.js version installed on your server
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      # NOTE: This step ensures your application builds successfully, 
      # using any necessary build-time secrets.
      - name: Build Next.js Application
        run: npm run build
        env:
          # Include all build-time environment variables here
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }} 

      # --- Deployment Stage: Transfer Built Files ---
      - name: Deploy Built Files via SFTP
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          
          # CRITICAL: DO NOT include .env here!
          SOURCE: .next/, public/, package.json, next.config.js, yarn.lock
          
          TARGET: /var/www/pantherarestlounge.com/ 
          
      # --- Process Management Stage: Create .env & Restart PM2 ---
      - name: Create .env File and Restart PM2 Process
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          
          # This script securely creates the .env file and starts the app.
          script: |
            cd /var/www/pantherarestlounge.com
            
            # 1. Create the secure .env file on the server using secrets
            echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env
            echo "ADMIN_CREATION_SECRET=${{ secrets.ADMIN_CREATION_SECRET }}" >> .env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
            echo "MAIL_USER=${{ secrets.MAIL_USER }}" >> .env
            echo "MAIL_PASS=${{ secrets.MAIL_PASS }}" >> .env
            echo "MAIL_HOST=${{ secrets.MAIL_HOST }}" >> .env
            echo "MAIL_PORT=${{ secrets.MAIL_PORT }}" >> .env
            echo "MAIL_SECURE=${{ secrets.MAIL_SECURE }}" >> .env
            echo "NOTIFY_EMAIL=${{ secrets.NOTIFY_EMAIL }}" >> .env
            echo "WHATSAPP_PHONE_ID=${{ secrets.WHATSAPP_PHONE_ID }}" >> .env
            echo "WHATSAPP_TOKEN=${{ secrets.WHATSAPP_TOKEN }}" >> .env
            echo "CLIENT_WHATSAPP_NUMBER=${{ secrets.CLIENT_WHATSAPP_NUMBER }}" >> .env
            
            # 2. Start/Reload PM2
            if pm2 describe panthera-app > /dev/null; then
              pm2 reload panthera-app
            else
              pm2 start npm --name "panthera-app" -- start
            fi
            pm2 save